
####################################################################
# Include Convey Makefile Template
####################################################################
include ../Makefile.include
#CNY_PDK_TB_USER_VLOG += ./tb_user.v
