
####################################################################
# Include Convey Makefile Template
####################################################################
include ../Makefile.include
VERILOG_COMPILE_OPTIONS += +define+ANALYSIS
#CNY_PDK_TB_USER_VLOG += ./tb_user.v
